common: &common
  username: zomg_ponies
  password:
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *common
  database: the_4_ponies_of_the_apocalypse_development
test:
  <<: *common
  database: the_4_ponies_of_the_apocalypse_test
production:
  <<: *common
  database: the_4_ponies_of_the_apocalypse_production
